name: Self-hosted Renovate

on:
  schedule:
    - cron: '21 * * * 1-5'
    - cron: '21 6,14,23 * * 0,6'
  workflow_dispatch: {}

env:
  cache_repos_dir: /tmp/renovate/cache/renovate/repository
  cache_repos_key: renovate-repos-cache

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest

    steps:
      - name: Cache Renovate repositories
        uses: actions/cache@v6
        id: cache-repos
        with:
          path: ${{ env.cache_repos_dir }}
          key: ${{ env.cache_repos_key }}.${{ gitea.run_id }}-${{ gitea.run_attempt }}
          restore_keys: |
            ${{ env.cache_repos_key }}.

      - name: Fix restore Renovate cache ownership
        if: steps.cache-repos.outputs.cache-matched-key != ''
        run: |
          sudo chown -R 12021:0 /tmp/renovate/
          ls -R "$cache_dir"

      - name: Run self-hosted Renovate
        uses: renovatebot/github-action@3064367f740a1a91cca218698a63902689cce200 # v46.1.20
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{ vars.RENOVATE_LOG_LEVEL || 'info' }}
          RENOVATE_AUTODISCOVER: true
          RENOVATE_ENDPOINT: ${{ secrets.RENOVATE_ENDPOINT }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
          RENOVATE_GIT_AUTHOR: ${{ vars.RENOVATE_GIT_AUTHOR }}
          RENOVATE_OPTIMIZE_FOR_DISABLED: true
          RENOVATE_PLATFORM: gitea
          # RENOVATE_REPOSITORIES: '[]'
          RENOVATE_REPOSITORY_CACHE: ${{ vars.RENOVATE_REPOSITORY_CACHE || 'enabled' }}
          RENOVATE_USERNAME: ${{ secrets.RENOVATE_USERNAME }}
