name: Self-hosted Renovate

on:
  schedule:
    - cron: '21 * * * 1-5'
    - cron: '21 6,14,23 * * 0,6'
  workflow_dispatch: {}

env:
  cache_repos_dir: /tmp/renovate/cache/renovate/repository
  cache_repos_key: renovate-repos-cache

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest

    steps:
      - name: Cache Renovate repositories
        uses: actions/cache@55cc8345863c7cc4c66a329aec7e433d2d1c52a9 # v6.1.0
        id: cache-repos
        with:
          path: ${{ env.cache_repos_dir }}
          key: ${{ env.cache_repos_key }}.${{ gitea.run_id }}-${{ gitea.run_attempt }}
          restore_keys: |
            ${{ env.cache_repos_key }}.${{ gitea.run_id }}-
            ${{ env.cache_repos_key }}.

      - name: Fix restore Renovate cache ownership
        if: steps.cache-repos.outputs.cache-matched-key != ''
        run: |
          if [ -d "/tmp/renovate/" ]; then
            echo "Fixing ownership: /tmp/renovate/"
            sudo chown -R 12021:0 /tmp/renovate/
          fi

          ls -R "$cache_repos_dir" || echo "Renovate repositories cache directory not found: $cache_repos_dir"

      - name: Run self-hosted Renovate
        uses: renovatebot/github-action@316d7cd859606d6039a2182b7d69199e9b036835 # v46.2.1
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          LOG_LEVEL: ${{ vars.RENOVATE_LOG_LEVEL || 'info' }}
          RENOVATE_AUTODISCOVER: true
          RENOVATE_ENDPOINT: ${{ secrets.RENOVATE_ENDPOINT }}
          RENOVATE_GITHUB_COM_TOKEN: ${{ secrets.RENOVATE_GITHUB_COM_TOKEN }}
          RENOVATE_GIT_AUTHOR: ${{ vars.RENOVATE_GIT_AUTHOR }}
          RENOVATE_OPTIMIZE_FOR_DISABLED: true
          RENOVATE_PLATFORM: gitea
          # RENOVATE_REPOSITORIES: '[]'
          RENOVATE_REPOSITORY_CACHE: ${{ vars.RENOVATE_REPOSITORY_CACHE || 'enabled' }}
          RENOVATE_USERNAME: ${{ secrets.RENOVATE_USERNAME }}
