name: Test

on:
  push:
    paths:
      - .gitea/workflows/test.yml
      - default.json
      - renovate.json
  pull_request:
    paths:
      - .gitea/workflows/test.yml
      - default.json
      - renovate.json
  workflow_dispatch: {}

env:
  cache-key-prefix: renovate-npm

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6

      - name: Setup pnpm
        uses: pnpm/action-setup@v6
        with:
          version: latest

      - name: Get pnpm cache directory
        id: pnpm-cache
        run: |
          PNPM_CACHE_DIR=$(pnpm store path)
          echo "PNPM_CACHE_DIR=$PNPM_CACHE_DIR" | tee -a $GITEA_OUTPUT

          echo "ls -R $PNPM_CACHE_DIR"
          ls -R "$PNPM_CACHE_DIR" || true

      - name: Test debug messages
        run: |
          echo "ls -R $PWD"
          ls -R . || true

          echo "~/.cache/pnpm"
          ls -R "~/.cache/pnpm" || true

          echo "~/.local/share/pnpm/store"
          ls -R "~/.local/share/pnpm/store" || true

      - name: Restore global pnpm assets cache
        id: npm-cache-restore
        uses: actions/cache/restore@v6
        with:
          path: ${{ steps.pnpm-cache.outputs.PNPM_CACHE_DIR }}
          key: ${{ env.cache-key-prefix }}-${{ hashFiles('.gitea/workflows/test.yml') }}
          restore-keys: |
            ${{ env.cache-key-prefix }}-

      - name: Test Renovate configuration files
        run: |
          renovate_files=(
            "default.json"
            "renovate.json"
          )

          CI=true pnpm dlx --package renovate renovate-config-validator --strict "${renovate_files[@]}"

      - name: Test debug messages
        run: |
          echo "ls -R $PWD"
          ls -R . || true

          echo "~/.cache/pnpm"
          ls -R "~/.cache/pnpm" || true

          echo "~/.local/share/pnpm/store"
          ls -R "~/.local/share/pnpm/store" || true

      - name: Save global pnpm assets cache
        uses: actions/cache/save@v6
        with:
          path: ${{ steps.pnpm-cache.outputs.PNPM_CACHE_DIR }}
          key: ${{ env.cache-key-prefix }}-${{ hashFiles('.gitea/workflows/test.yml') }}
