name: Test

on:
  push:
    paths:
      - .gitea/workflows/test.yml
      - default.json
      - renovate.json
  pull_request:
    paths:
      - .gitea/workflows/test.yml
      - default.json
      - renovate.json
  workflow_dispatch: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/renovatebot/renovate:44.29.2@sha256:d0c00f5e19d0042c5a3e48c5fb949bd6ce3ea4f687cb4880370cb246082d1902

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Test Renovate configuration files
        run: |
          renovate_files=(
            "default.json"
            "renovate.json"
          )

          renovate-config-validator --strict "${renovate_files[@]}"
