name: Test

on:
  push:
    paths:
      - .gitea/workflows/test.yml
      - default.json
      - renovate.json
  pull_request:
    paths:
      - .gitea/workflows/test.yml
      - default.json
      - renovate.json
  workflow_dispatch: {}

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/renovatebot/renovate:44.30.1@sha256:c306f0d611ec5a053062d8f2adcd0634b75d55338820f80c8b79759d316466bc

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Test Renovate configuration files
        run: |
          renovate_files=(
            "default.json"
            "renovate.json"
          )

          renovate-config-validator --strict "${renovate_files[@]}"
