name: Test

on:
  push:
    paths:
      - .github/workflows/test.yml
      - default.json
      - renovate.json
  pull_request:
    paths:
      - .github/workflows/test.yml
      - default.json
      - renovate.json
  workflow_dispatch: {}

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        config:
          - file: default.json
          - file: renovate.json

    steps:
      - name: Checkout Git repository
        uses: actions/checkout@v6

      - name: Cache global npm assets
        id: npm-cache
        uses: actions/cache@v6
        with:
          paths: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles(job.workflow_file_path) }}
          restore_keys: |
            ${{ runner.os }}-npm-

      - name: Test Renovate configuration file - ${{ matrix.config.file }}
        run: |
          RENOVATE_CONFIG_FILE="${{ matrix.config.file }}" npx --yes -p renovate renovate-config-validator
